services:
  gateway-0:
    image: keyostar:local
    environment:
      KEYOSTAR_INSTANCE_MODE: GATEWAY
      KEYOSTAR_GATEWAY_ADDRESSING: docker
      KEYOSTAR_GATEWAY_HASH_FUNCTION: java
      KEYOSTAR_GATEWAY_STORE_COUNT: 3

      KEYOSTAR_DOCKER_STORE_HOST_TEMPLATE: store-%d
      KEYOSTAR_DOCKER_STORE_PORT: 8080

      SERVER_PORT: 8080

    ports:
      - "8080:8080"

  store-0:
    image: keyostar:local
    environment:
      KEYOSTAR_INSTANCE_MODE: STORE
      SERVER_PORT: 8080
    ports:
      - "9080:8080"

  store-1:
    image: keyostar:local
    environment:
      KEYOSTAR_INSTANCE_MODE: STORE
      SERVER_PORT: 8080
    ports:
      - "9081:8080"

  store-2:
    image: keyostar:local
    environment:
      KEYOSTAR_INSTANCE_MODE: STORE
      SERVER_PORT: 8080
    ports:
      - "9082:8080"