spring.application.name=keyostar

keyostar.instance.mode=GATEWAY

keyostar.gateway.addressing=localhost
keyostar.gateway.hash-function=java
keyostar.gateway.store-count=3

keyostar.localhost.store-base-port=9080
keyostar.docker.store-port=8080
keyostar.docker.store-host-template=store-%d
keyostar.kubernetes.store-stateful-set-name=my-keyostar-store-statefulset
keyostar.kubernetes.store-service-name=my-keyostar-store-service
keyostar.kubernetes.store-port=8080

keyostar.observability.logger=console
keyostar.observability.log-level=trace
