spring.application.name=valonis
valonis.instance.mode=GATEWAY

valonis.gateway.base-url=http://localhost
valonis.gateway.base-port=8080
valonis.gateway.count=1
valonis.gateway.hash-function=java
valonis.gateway.address-resolver=sequential-ports

valonis.store.base-url=http://localhost
valonis.store.base-port=9080
valonis.store.count=1
