spring.application.name=valonis

valonis.instance.mode=GATEWAY

valonis.gateway.addressing=localhost
valonis.gateway.hash-function=java
valonis.gateway.store-count=3

valonis.localhost.store-base-port=9080
valonis.docker.store-port=8080
valonis.docker.store-host-template=store-%d
valonis.kubernetes.store-stateful-set-name=valonis-store
valonis.kubernetes.store-service-name=valonis-store
valonis.kubernetes.store-port=8080

valonis.observability.logger=console
valonis.observability.log-level=trace
