apiVersion: apps/v1
kind: Deployment
metadata:
  name: keyostar-gateway

spec:
  replicas: 2

  selector:
    matchLabels:
      app: keyostar
      role: gateway

  template:
    metadata:
      labels:
        app: keyostar
        role: gateway

    spec:
      containers:
        - name: keyostar
          image: keyostar:local

          ports:
            - containerPort: 8080

          env:
            - name: KEYOSTAR_INSTANCE_MODE
              value: GATEWAY

            - name: KEYOSTAR_GATEWAY_ADDRESSING
              value: kubernetes

            - name: KEYOSTAR_GATEWAY_HASH_FUNCTION
              value: java

            - name: KEYOSTAR_GATEWAY_STORE_COUNT
              value: "3"

            - name: KEYOSTAR_KUBERNETES_STORE_STATEFUL_SET_NAME
              value: keyostar-store

            - name: KEYOSTAR_KUBERNETES_STORE_SERVICE_NAME
              value: keyostar-store

            - name: KEYOSTAR_KUBERNETES_STORE_PORT
              value: "8080"

            - name: SERVER_PORT
              value: "8080"