apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keyostar-store

spec:
  serviceName: keyostar-store

  replicas: 3

  selector:
    matchLabels:
      app: keyostar
      role: store

  template:
    metadata:
      labels:
        app: keyostar
        role: store

    spec:
      containers:
        - name: keyostar
          image: keyostar:local

          ports:
            - containerPort: 8080

          env:
            - name: KEYOSTAR_INSTANCE_MODE
              value: STORE

            - name: SERVER_PORT
              value: "8080"